### ISSUE TITLE
Allow Notification Center Rearragement

### ISSUE THREAD

**Issue by insanj** [RinseDev/Orangered#5]
Every respring, the Orangered notification provider is reinitialized (or in some way destructive in its integration), forcing any manual ordering the user performs on the Reddit client listed in the Notification Center preferences to be trashed.

**Comment by tateu** [comment]
How about this: https://github.com/tateu/Orangered/commit/8bdd3162f900bfaf078820b0962a1fab57892736

I'm not sure what the purpose of _addActiveSectionID and _removeActiveSectionID is. They don't seem to do anything on my device except cause the Orangered client to reset to the top in Notification Center after every reboot/respring.
